services:
  postgres:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: jdin
      POSTGRES_PASSWORD: jdin
      POSTGRES_DB: jdin
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  bot:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        # DEV_MODE is determined by environment variable, default true
        DEV_MODE: "${DEV_MODE:-true}"
    environment:
      - ENV=${ENV:-development}
    volumes:
      # Only mount source code if in dev mode
      - type: bind
        source: .
        target: /app
        read_only: ${DEV_MODE:-true} != "false"  # pseudo logic
    depends_on:
      - postgres
    env_file:
      - .env
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    ports:
      - "8000:8000"

volumes:
  pgdata: