services:
  postgres:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: dino
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: dino_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  bot:
    build:
      context: .
      dockerfile: Dockerfile
      args:
         APP_USER: "dino"
         APP_UID: "1001"
         APP_GID: "1001"
         PYTHON_VERSION: "3.13"
         POETRY_VERSION: "2.1.4"   # optional
    image: app:latest
    depends_on:
      - postgres
    env_file:
      - .env
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    ports:
      - "8000:8000"
    restart: unless-stopped

volumes:
  pgdata: