services:
  bot:
    image: jdinbot:latest
    ports:
      - "8000:8000"
    environment:
      - ENV=production
    command: uvicorn jdinbot.main:jdinbot --host 0.0.0.0 --port 8000 --workers 4
    deploy:
      restart_policy:
        condition: on-failure
